### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by FellFromTheSky** [bspkrs/MCPMappingViewer#21] opened 2020-03-26 00:31 UTC
It's not working anymore. I'm unable to download mappings with it.
Please fix it.
Thanks.

**Comment by VinyarionHyarmendacil** [comment] 2020-04-02 19:04
This appears to be a duplicate of issue #18, from the extremely detailed description of the problem provided.

**Comment by FellFromTheSky** [comment] 2020-05-30 21:07
Yes, it is, I wasn't able to print the logs.
Sorry.

**Closed** 2020-05-30 21:06 UTC
